// Do not edit, this is generated file.
// fetch from https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements
// last update at 4/17/2025, 1:26:16 PM GMT+6:30

import type { HTMLTagNames } from "./types.js";

export type HTMLTags = {
  main_root: { elements: HTMLTagNames[] };
  document_metadata: { elements: HTMLTagNames[] };
  sectioning_root: { elements: HTMLTagNames[] };
  content_sectioning: { elements: HTMLTagNames[] };
  text_content: { elements: HTMLTagNames[] };
  inline_text_semantics: { elements: HTMLTagNames[] };
  image_and_multimedia: { elements: HTMLTagNames[] };
  embedded_content: { elements: HTMLTagNames[] };
  svg_and_mathml: { elements: HTMLTagNames[] };
  scripting: { elements: HTMLTagNames[] };
  demarcating_edits: { elements: HTMLTagNames[] };
  table_content: { elements: HTMLTagNames[] };
  forms: { elements: HTMLTagNames[] };
  interactive_elements: { elements: HTMLTagNames[] };
  web_components: { elements: HTMLTagNames[] };
  obsolete_and_deprecated_elements: { elements: HTMLTagNames[] };
  void_elements: { elements: HTMLTagNames[] };
  all_mdn_elements: { elements: HTMLTagNames[] };
};

export const htmlTags: HTMLTags = {
  main_root: {
    elements: ["html"],
  },
  document_metadata: {
    elements: [
      "base",
      "head",
      "link",
      "meta",
      "base",
      "link",
      "script",
      "style",
      "title",
      "style",
      "title",
    ],
  },
  sectioning_root: {
    elements: ["body"],
  },
  content_sectioning: {
    elements: [
      "address",
      "article",
      "aside",
      "footer",
      "header",
      "h1",
      "h2",
      "h3",
      "h4",
      "h5",
      "h6",
      "hgroup",
      "main",
      "nav",
      "section",
      "search",
    ],
  },
  text_content: {
    elements: [
      "blockquote",
      "cite",
      "dd",
      "dt",
      "dl",
      "div",
      "dl",
      "dt",
      "dd",
      "dt",
      "dl",
      "dd",
      "dd",
      "figcaption",
      "figure",
      "figure",
      "figcaption",
      "hr",
      "li",
      "ol",
      "ul",
      "menu",
      "menu",
      "ul",
      "ul",
      "li",
      "ol",
      "p",
      "pre",
      "ul",
    ],
  },
  inline_text_semantics: {
    elements: [
      "a",
      "abbr",
      "b",
      "strong",
      "bdi",
      "bdo",
      "br",
      "cite",
      "code",
      "data",
      "dfn",
      "p",
      "dt",
      "dd",
      "em",
      "i",
      "kbd",
      "mark",
      "q",
      "blockquote",
      "rp",
      "ruby",
      "rt",
      "rt",
      "ruby",
      "ruby",
      "s",
      "del",
      "ins",
      "samp",
      "small",
      "span",
      "strong",
      "sub",
      "sup",
      "time",
      "u",
      "var",
      "wbr",
    ],
  },
  image_and_multimedia: {
    elements: ["area", "audio", "img", "map", "area", "track", "video"],
  },
  embedded_content: {
    elements: [
      "embed",
      "fencedframe",
      "iframe",
      "object",
      "picture",
      "source",
      "img",
      "source",
    ],
  },
  svg_and_mathml: {
    elements: ["svg", "math"],
  },
  scripting: {
    elements: ["canvas", "noscript", "script"],
  },
  demarcating_edits: {
    elements: ["del", "ins"],
  },
  table_content: {
    elements: [
      "caption",
      "col",
      "colgroup",
      "colgroup",
      "colgroup",
      "table",
      "tbody",
      "tr",
      "td",
      "tr",
      "tfoot",
      "tr",
      "th",
      "tr",
      "thead",
      "tr",
      "th",
      "tr",
      "td",
      "th",
    ],
  },
  forms: {
    elements: [
      "button",
      "datalist",
      "option",
      "fieldset",
      "label",
      "form",
      "input",
      "label",
      "legend",
      "fieldset",
      "meter",
      "optgroup",
      "select",
      "option",
      "optgroup",
      "datalist",
      "output",
      "progress",
      "select",
      "selectedcontent",
      "textarea",
    ],
  },
  interactive_elements: {
    elements: ["details", "summary", "dialog", "summary", "details"],
  },
  web_components: {
    elements: ["slot", "template"],
  },
  obsolete_and_deprecated_elements: {
    elements: [
      "acronym",
      "big",
      "center",
      "slot",
      "slot",
      "dir",
      "ul",
      "font",
      "frame",
      "frameset",
      "frameset",
      "frame",
      "img",
      "marquee",
      "nobr",
      "noembed",
      "object",
      "noframes",
      "frame",
      "param",
      "object",
      "plaintext",
      "rb",
      "rtc",
      "rb",
      "ruby",
      "rb",
      "rt",
      "rtc",
      "slot",
      "strike",
      "tt",
      "xmp",
    ],
  },
  void_elements: {
    elements: [
      "area",
      "base",
      "br",
      "col",
      "embed",
      "hr",
      "img",
      "input",
      "link",
      "meta",
      "param",
      "source",
      "track",
      "wbr",
    ],
  },
  all_mdn_elements: {
    elements: [
      "html",
      "base",
      "head",
      "link",
      "meta",
      "base",
      "link",
      "script",
      "style",
      "title",
      "style",
      "title",
      "body",
      "address",
      "article",
      "aside",
      "footer",
      "header",
      "h1",
      "h2",
      "h3",
      "h4",
      "h5",
      "h6",
      "hgroup",
      "main",
      "nav",
      "section",
      "search",
      "blockquote",
      "cite",
      "dd",
      "dt",
      "dl",
      "div",
      "dl",
      "dt",
      "dd",
      "dt",
      "dl",
      "dd",
      "dd",
      "figcaption",
      "figure",
      "figure",
      "figcaption",
      "hr",
      "li",
      "ol",
      "ul",
      "menu",
      "menu",
      "ul",
      "ul",
      "li",
      "ol",
      "p",
      "pre",
      "ul",
      "a",
      "abbr",
      "b",
      "strong",
      "bdi",
      "bdo",
      "br",
      "cite",
      "code",
      "data",
      "dfn",
      "p",
      "dt",
      "dd",
      "em",
      "i",
      "kbd",
      "mark",
      "q",
      "blockquote",
      "rp",
      "ruby",
      "rt",
      "rt",
      "ruby",
      "ruby",
      "s",
      "del",
      "ins",
      "samp",
      "small",
      "span",
      "strong",
      "sub",
      "sup",
      "time",
      "u",
      "var",
      "wbr",
      "area",
      "audio",
      "img",
      "map",
      "area",
      "track",
      "video",
      "embed",
      "fencedframe",
      "iframe",
      "object",
      "picture",
      "source",
      "img",
      "source",
      "svg",
      "math",
      "canvas",
      "noscript",
      "script",
      "del",
      "ins",
      "caption",
      "col",
      "colgroup",
      "colgroup",
      "colgroup",
      "table",
      "tbody",
      "tr",
      "td",
      "tr",
      "tfoot",
      "tr",
      "th",
      "tr",
      "thead",
      "tr",
      "th",
      "tr",
      "td",
      "th",
      "button",
      "datalist",
      "option",
      "fieldset",
      "label",
      "form",
      "input",
      "label",
      "legend",
      "fieldset",
      "meter",
      "optgroup",
      "select",
      "option",
      "optgroup",
      "datalist",
      "output",
      "progress",
      "select",
      "selectedcontent",
      "textarea",
      "details",
      "summary",
      "dialog",
      "summary",
      "details",
      "slot",
      "template",
      "acronym",
      "big",
      "center",
      "slot",
      "slot",
      "dir",
      "ul",
      "font",
      "frame",
      "frameset",
      "frameset",
      "frame",
      "img",
      "marquee",
      "nobr",
      "noembed",
      "object",
      "noframes",
      "frame",
      "param",
      "object",
      "plaintext",
      "rb",
      "rtc",
      "rb",
      "ruby",
      "rb",
      "rt",
      "rtc",
      "slot",
      "strike",
      "tt",
      "xmp",
    ],
  },
};
